"""B2.3 Usage/Metering — pure data contracts.

No financial math. No verification truth. No billing engine.
Usage events are append-only observability records.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

USAGE_SCHEMA = "FINCO_USAGE_EVENT_V1"
USAGE_AUTHORITY = "B2_3_V1"

# ── Feature keys ──────────────────────────────────────────────────────────────────────────────
# Generic keys; MCP integration is a hook/interface only in V1.

FEATURE_INSTITUTIONAL_API_REQUEST = "institutional_api_request"
FEATURE_MCP_TOOL_CALL = "mcp_tool_call"          # hook interface only
FEATURE_XLSX_EXPORT = "xlsx_export"
FEATURE_TRUST_PACK_ACCESS = "trust_pack_access"   # hook interface only

ALL_FEATURE_KEYS: frozenset[str] = frozenset({
    FEATURE_INSTITUTIONAL_API_REQUEST,
    FEATURE_MCP_TOOL_CALL,
    FEATURE_XLSX_EXPORT,
    FEATURE_TRUST_PACK_ACCESS,
})

# ── Safe metadata keys ────────────────────────────────────────────────────────────────────
# Only these keys are permitted in UsageEvent.metadata. Any other key is
# stripped silently. RPC URLs, secrets, and wallet addresses are never stored.

SAFE_METADATA_KEYS: frozenset[str] = frozenset({
    "project_id",
    "project_type",
    "api_version",
    "export_format",
    "feature_variant",
    "session_type",
})

# Keys that are explicitly forbidden — extra guard beyond the allowlist.
_FORBIDDEN_METADATA_KEYS: frozenset[str] = frozenset({
    "rpc_url", "token_address", "wallet_address", "private_key",
    "secret", "password", "api_key", "balance_raw", "balance",
    "rpc", "endpoint",
})


def _sanitise_metadata(raw: dict[str, Any]) -> dict[str, Any]:
    """Return a copy of metadata containing only safe, non-secret fields."""
    if not raw:
        return {}
    result: dict[str, Any] = {}
    for k, v in raw.items():
        k_lower = k.lower()
        if k_lower in _FORBIDDEN_METADATA_KEYS:
            continue
        if k not in SAFE_METADATA_KEYS:
            continue
        if not isinstance(v, (str, int, float, bool, type(None))):
            v = str(v)
        result[k] = v
    return result


@dataclass(frozen=True)
class UsageEvent:
    """Immutable record of one metered usage occurrence.

    subject_id is always derived from a signed session; callers cannot
    supply it directly. wallet_address is included only when already
    linked to the session via the B2.2 wallet_auth layer.
    """

    event_id: str          # UUID, generated by the recorder
    idempotency_key: str   # caller-supplied; uniqueness enforced by storage
    subject_id: str        # from signed session — never caller-controlled
    wallet_address: str | None  # optional canonically-linked wallet identity
    feature_key: str
    quantity: int
    unit: str              # e.g. "request", "export", "access"
    occurred_at: datetime  # caller-supplied event time (must be tz-aware)
    recorded_at: datetime  # wall clock at recording time (must be tz-aware)
    authority: str = USAGE_AUTHORITY
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.event_id or not self.idempotency_key:
            raise ValueError("event_id and idempotency_key are required")
        if not self.subject_id:
            raise ValueError("subject_id is required")
        if self.feature_key not in ALL_FEATURE_KEYS:
            raise ValueError(f"unknown feature_key: {self.feature_key!r}")
        if not isinstance(self.quantity, int) or isinstance(self.quantity, bool) or self.quantity < 1:
            raise ValueError("quantity must be a positive integer")
        if not self.unit.strip():
            raise ValueError("unit is required")
        if self.occurred_at.tzinfo is None or self.occurred_at.utcoffset() is None:
            raise ValueError("occurred_at must be timezone-aware")
        if self.recorded_at.tzinfo is None or self.recorded_at.utcoffset() is None:
            raise ValueError("recorded_at must be timezone-aware")
        # Sanitise metadata in-place (frozen dataclass: use object.__setattr__)
        object.__setattr__(self, "metadata", _sanitise_metadata(self.metadata))


@dataclass(frozen=True)
class UsageSummary:
    """Read-only usage summary for one (subject, feature_key, period) slice."""

    subject_id: str
    feature_key: str
    total_quantity: int
    event_count: int
    period_start: datetime | None = None
    period_end: datetime | None = None

    def __post_init__(self) -> None:
        if not self.subject_id:
            raise ValueError("subject_id is required")
        if self.feature_key not in ALL_FEATURE_KEYS:
            raise ValueError(f"unknown feature_key: {self.feature_key!r}")
        if self.total_quantity < 0 or self.event_count < 0:
            raise ValueError("totals must be non-negative")
