"""Networked R12 proof: Digital Twin from independently verified R11 evidence.

Consumes the ONE canonical R11 evidence object produced by the frozen R11
implementation (`finco_radar.r11.live_proof`) and constructs the Digital
Twin from that exact object — no independent R11 regeneration (A11).

R12 gitHead provenance (A12): the outer R12 artifact records the actual
R12 HEAD producing the artifact, obtained via the repository-approved
`_git_head` helper; the R11 subject keeps its own gitHead inside
`subjectR11Evidence`.
"""
from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

from finco_radar.r3.live_proof import _git_head
from finco_radar.digital_twin.contracts import (
    verify_serialized_r12_evidence,
)
from finco_radar.digital_twin.twin import build_digital_twin

EVIDENCE_PATH = "artifacts/radar_r12_digital_twin_evidence.json"
SHA256_PATH = "artifacts/radar_r12_digital_twin_evidence.sha256"
MANIFEST_PATH = "artifacts/radar_r12_digital_twin_manifest.json"
DEFAULT_R11_EVIDENCE_PATH = "artifacts/radar_r11_verification_evidence.json"


def main() -> int:
    # A11: consume the ONE canonical R11 evidence object generated by the
    # frozen R11 live proof — never regenerate a semantically equivalent
    # R11 object here.
    r11_evidence_path = Path(os.getenv(
        "RADAR_R11_EVIDENCE_PATH", DEFAULT_R11_EVIDENCE_PATH))
    r11_evidence = json.loads(
        r11_evidence_path.read_text(encoding="utf-8"))
    r11_recorded_digest = r11_evidence.get("r11SnapshotDigest")
    if not isinstance(r11_recorded_digest, str) or not r11_recorded_digest:
        raise RuntimeError(
            "consumed R11 artifact carries no r11SnapshotDigest")

    # A12: outer R12 gitHead is R12 artifact-generation provenance — the
    # exact current HEAD, never copied from the embedded R11 subject.
    git_head = _git_head()

    twin = build_digital_twin(
        r11_evidence=r11_evidence,
        generated_at=datetime.now(timezone.utc),
        git_head=git_head,
    )
    evidence = twin.to_evidence_dict()

    # A11: canonical object equality — the embedded R11 subject must BE
    # the consumed object, digest-identical.
    if evidence["subjectR11Evidence"] != r11_evidence:
        raise RuntimeError(
            "embedded subjectR11Evidence is not the consumed canonical "
            "R11 object")
    if evidence["subjectR11Evidence"]["r11SnapshotDigest"] != (
        r11_recorded_digest
    ):
        raise RuntimeError("embedded R11 snapshot digest mismatch")
    # Serialized replay verification must pass before the artifact exists.
    if not verify_serialized_r12_evidence(evidence):
        raise RuntimeError("serialized R12 replay verification failed")

    first = json.dumps(evidence, indent=2, sort_keys=True, ensure_ascii=False)
    second = json.dumps(json.loads(first), indent=2, sort_keys=True,
                        ensure_ascii=False)
    if first != second:
        raise RuntimeError(
            "R12 evidence serialization is not byte-deterministic")
    evidence_path = Path(os.getenv("RADAR_R12_EVIDENCE_PATH", EVIDENCE_PATH))
    evidence_path.parent.mkdir(parents=True, exist_ok=True)
    evidence_path.write_text(first + "\n", encoding="utf-8")
    digest = hashlib.sha256(evidence_path.read_bytes()).hexdigest()
    Path(os.getenv("RADAR_R12_SHA256_PATH", SHA256_PATH)).write_text(
        f"{digest}  {evidence_path.name}\n", encoding="utf-8")

    # A11: manifest lineage — R10 snapshot digest is the verified R11
    # subject binding (subjectSnapshotDigest == subjectEvidence
    # .r10SnapshotDigest), never a non-authoritative outer field.
    r11_subject = evidence["subjectR11Evidence"]
    checks = r11_subject.get("checks", [])
    failed_check_count = sum(1 for c in checks if c.get("state") == "FAIL")
    unavailable_check_count = sum(
        1 for c in checks if c.get("state") == "UNAVAILABLE")
    subject_gaps = sorted(g["gapKind"] for g in evidence["upstreamGaps"])
    manifest = {
        "schemaVersion": evidence["schemaVersion"],
        "phase": evidence["phase"],
        "gitHead": evidence["gitHead"],
        "producedAt": evidence["generatedAt"],
        "status": evidence["status"],
        "economicAssetUid": evidence["economicAssetUid"],
        "economicNodeId": evidence["economicNodeId"],
        "twinId": evidence["twinId"],
        "r12SnapshotDigest": evidence["r12SnapshotDigest"],
        "r11SnapshotDigest": r11_subject.get("r11SnapshotDigest"),
        "r10SnapshotDigest": r11_subject.get("subjectSnapshotDigest"),
        "evidenceJsonSha256": digest,
        "r11FreezeAnchor": evidence["freezeAnchor"],
        "r11FreezeTree": evidence["freezeTree"],
        "componentCount": len(evidence["components"]),
        "failedCheckCount": failed_check_count,
        "unavailableCheckCount": unavailable_check_count,
        "synthetic": evidence["synthetic"],
        "boundaries": evidence["boundaries"],
        "note": (
            "R12 composes a deterministic state representation from the "
            "verified R11 evidence; DIGITAL_TWIN status is composition "
            "completeness only, not source truth, market freshness, model "
            "correctness or economic comparability."),
    }
    Path(os.getenv("RADAR_R12_MANIFEST_PATH", MANIFEST_PATH)).write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "status": evidence["status"],
        "twinId": evidence["twinId"],
        "subjectStatus": r11_subject.get("status"),
        "subjectGaps": subject_gaps,
        "gitHead": evidence["gitHead"],
        "digest": digest,
        "evidence": str(evidence_path),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
