#!/usr/bin/env python3
"""Render docs/readiness/*.md from the trust registry (WF-10A).

    python tools/render_readiness_docs.py           # write the files
    python tools/render_readiness_docs.py --check   # exit 1 if any file is out of date

The registry is the source of truth; these files are generated and must not be edited by hand.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.trust_readiness import projection as P  # noqa: E402
from app.trust_readiness import registry as R  # noqa: E402
from app.trust_readiness.contracts import STATUS_LABEL  # noqa: E402

OUT = ROOT / "docs" / "readiness"
BANNER = (
    "<!-- GENERATED by tools/render_readiness_docs.py from app/trust_readiness/registry.py. "
    "Do not edit by hand. -->\n"
)
FOOTER = (
    f"\n---\nReviewed {R.REVIEWED_ON}. {R.SCOPE_STATEMENT} This document describes the product. "
    "It is not a legal document, an audit opinion or a certification.\n"
)


def _cell(text: str) -> str:
    return " ".join(str(text).replace("|", "/").split())


def _ev(item) -> str:
    return "; ".join(f"{e.kind.value} `{e.path}`" for e in item.evidence) or "none"


def _items(items) -> str:
    out = []
    for i in items:
        out.append(f"### {i.title}\n\n**{STATUS_LABEL[i.status]}.** {i.statement}\n")
        if i.limitation:
            out.append(f"Limit: {i.limitation}\n")
        out.append(f"Evidence: {_ev(i)}\n")
    return "\n".join(out)


def _gaps(gaps) -> str:
    return "\n".join(
        f"### {g.title}\n\n**{g.severity.value.title()} severity.** {g.statement}\n\n"
        f"Recommended action: {g.recommended_action}\n\nEvidence: {_ev(g)}\n"
        for g in gaps
    )


def _legend() -> str:
    return "\n".join(f"- **{s['label']}**: {s['meaning']}" for s in P.status_legend()) + "\n"


def _doc(title: str, lede: str, body: str) -> str:
    return f"{BANNER}# {title}\n\n{lede}\n\n{body}{FOOTER}"


def build() -> dict[str, str]:
    docs: dict[str, str] = {}
    by_area = P.items_by_area(R.CONTROLS)

    def area_sections(areas) -> str:
        return "\n".join(f"## {R.AREA_LABELS[a]}\n\n{_items(by_area[a])}" for a in areas if a in by_area)

    docs["01_security_overview.md"] = _doc(
        "Product security overview",
        "The controls the FINCO Model product has today, each tied to code and a test.",
        "## Status labels\n\n" + _legend() + "\n" + area_sections(("security_controls", "operations"))
        + "\n## What is not claimed\n\n" + "\n".join(f"- **{n.label}:** {n.statement}" for n in R.NOT_CLAIMED) + "\n",
    )

    rows = "\n".join(
        f"| {_cell(d.data_category)} | {_cell(d.store)} | {_cell(d.tenant_key)} | "
        f"{'Yes' if d.may_contain_user_text else 'No'} | {_cell(d.contents)} | {STATUS_LABEL[d.status]} |"
        for d in R.DATA_STORES
    )
    docs["02_data_handling.md"] = _doc(
        "Data handling and privacy",
        "What the product stores, where, and what it can contain. Facts for counsel; not a privacy notice.",
        "| Data | Stored in | Keyed by | May contain user text | Contents | Status |\n|---|---|---|---|---|---|\n"
        + rows + "\n",
    )

    docs["03_known_limitations_and_support_matrix.md"] = _doc(
        "Known limitations and support matrix",
        "Derived from `app/product_capability.py`, so it follows the product.",
        "| Vertical | Status | Reference | Run | Clone | Edit working copy | Last Run | API | Export |\n"
        "|---|---|---|---|---|---|---|---|---|\n"
        + "\n".join(
            f"| {r['name']} | {r['status'].replace('_', ' ').title()} | "
            + " | ".join("Yes" if f else "No" for f in (
                r["reference"], r["runnable"], r["cloneable"], r["editable"], r["last_run"], r["api"], r["export"]))
            + " |" for r in P.support_matrix())
        + "\n\n## Known gaps\n\n" + _gaps(P.known_gaps_sorted()),
    )

    docs["04_supported_and_unavailable.md"] = _doc(
        "Supported and unavailable features",
        "What a reader might assume exists but does not today.",
        "| Feature | State | Detail |\n|---|---|---|\n"
        + "\n".join(f"| {_cell(u['name'])} | {_cell(u['state'])} | {_cell(u['detail'])} |" for u in P.unavailable_features())
        + "\n",
    )

    docs["05_run_evidence.md"] = _doc(
        "Run evidence and integrity",
        "What a run check proves, what a signed certificate proves, and what neither proves.",
        "## Integrity checks (read from the implementation)\n\n"
        + "\n".join(f"- `{c['id']}`: {c['title']}" for c in P.integrity_checks())
        + "\n\n" + area_sections(("run_evidence",)),
    )

    docs["06_retention_and_deletion.md"] = _doc(
        "Retention and deletion inventory",
        "How long each category of data is kept and how it is removed today. Not a retention commitment.",
        "| Data | Retention rule | Deletion path | Automatic |\n|---|---|---|---|\n"
        + "\n".join(f"| {_cell(d.data_category)} | {_cell(d.retention_rule)} | {_cell(d.deletion_path)} | "
                    f"{'Yes' if d.automatic_deletion else 'No'} |" for d in R.DATA_STORES)
        + "\n",
    )

    docs["07_authentication_and_tenant_audit.md"] = _doc(
        "Authentication and tenant-control audit",
        "One operator account from the environment plus anonymous signed demo sessions.",
        area_sections(("access_control", "tenant_isolation")),
    )

    docs["08_release_readiness_checklist.md"] = _doc(
        "Release-readiness checklist",
        "Grouped by what it takes to close each item.",
        "\n".join(f"## {STATUS_LABEL[s]}\n\n{_items(items)}" for s, items in P.items_by_status(R.RELEASE_CHECKLIST).items() if items)
        + "\n## Legal documents\n\n"
        + "\n".join(f"- **{d.title}**: not published. Needs {d.approval_required.lower()}." for d in R.LEGAL_DOCUMENTS) + "\n",
    )

    index = "\n".join(f"- [{name}]({name})" for name in sorted(docs))
    docs["README.md"] = _doc(
        "Readiness pack",
        "Generated from the trust registry. The same content is served at `/trust`.",
        index + "\n",
    )
    return docs


def main(argv: list[str]) -> int:
    docs = build()
    if "--check" in argv:
        stale = [n for n, t in docs.items() if not (OUT / n).exists() or (OUT / n).read_text(encoding="utf-8") != t]
        extra = [p.name for p in OUT.glob("*.md") if p.name not in docs] if OUT.exists() else []
        for n in stale + extra:
            print(f"out of date: docs/readiness/{n}")
        return 1 if stale or extra else 0
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in docs.items():
        (OUT / name).write_text(text, encoding="utf-8")
    print(f"wrote {len(docs)} files to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
